# Generated by Django 4.2 on 2023-05-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_rename_tauthor_topic_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='tauthor',
        ),
    ]
